#!/bin/sh

while read -r file; do
  case "$1" in
    w) setbg "$file" & ;;
    r) convert -rotate 90 "$file" "$file" ;;
    R) convert -rotate -90 "$file" "$file" ;;
    f) convert -flop "$file" "$file" ;;
    F) convert -flip "$file" "$file" ;;
    y) printf "%s" "$file" | tr -d '\n' | xclip -se clip ;;
    g) ifinstalled gimp && setsid -f gimp "$file" ;;
  esac
done
