#!/bin/sh

while read -r file; do
  case "$1" in
    greater)    magick "$file" -rotate 90 "$file" ;;
    question)   magick "$file" -rotate 180 "$file" ;;
    less)       magick "$file" -rotate 270 "$file" ;;
    bar)        magick "$file" -flop "$file" ;;
    minus)      magick "$file" -flip "$file" ;;
    Home)       setbg "$file" &;;
    Delete)     rm "$file" ;;
    C-c)        printf "%s" "$file" | tr -d '\n' | xclip -se clip ;;
  esac
done
