#!/bin/sh

# multi-monitor management
main="$(dual_head get_main)"
if hdmi="$(dual_head get_hdmi)"; then
  bspc monitor "$hdmi" -d 1 2 3 4
  bspc monitor "$main" -d 5 6 7 8 9 10
  bspc wm -O "$hdmi" "$main"
else
  bspc monitor $main -d 1 2 3 4 5 6 7 8 9 10
fi

# autostart
copyq &
~/.config/polybar/launch &
setbg

# enable mouse for moving and resizing nodes
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
