import = ["~/.config/alacritty/dracula.toml"]

[cursor]
blink_interval = 700
blink_timeout = 0

[cursor.style]
blinking = "On"

[font]
size = 10.0

[font.bold]
family = "Iosevka Fixed"
style = "Bold"

[font.bold_italic]
family = "Iosevka Fixed"
style = "Bold Italic"

[font.italic]
family = "Iosevka Fixed"
style = "Italic"

[font.normal]
family = "Iosevka Fixed"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
opacity = 0.9
startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
