#!/bin/sh

# terminate running polybars
while pgrep -x polybar >/dev/null; do killall -q polybar; done

# base path for script files
export POLYBAR_SCRIPTS="$(dirname $0)/scripts"

# launch main bar
MAIN_POLYBAR="$(dual_head main)" && export MAIN_POLYBAR && polybar main &

# launch extra bar if 2nd window is attached
EXTRA_POLYBAR="$(dual_head extra)" && export EXTRA_POLYBAR && polybar extra &
