#!/bin/sh

is_full=0
sleep_pid=0

toggle() {
  is_full=$(( (is_full + 1) % 2 ))
}

print() {
  if [ $is_full -eq 0 ]; then
    date +"%H:%M:%S"
  else
    date +"%b %d (%a) %H:%M:%S"
  fi
}

trap "toggle" USR1

while true; do
  print
  sleep 1 &
  sleep_pid=$!
  wait
done
