#!/bin/sh

show_wifi=false
show_speed=false

toggle_wifi() {
  $show_wifi && show_wifi=false || show_wifi=true
}

toggle_speed() {
  $show_speed && show_speed=false || show_speed=true
}

status() {
  #speed
  if $show_speed; then
    net_speed
  fi
  
  
  # wifi
  if grep -xq 'up' /sys/class/net/w*/operstate 2>/dev/null; then
    # wifi is connected
    if $show_wifi; then
      printf "$(awk '/^\s*w/ { print int($3 * 100 / 70) "%% " }' /proc/net/wireless)"
      printf "$(iwgetid -r) "
    fi
    printf "󰀂"
  elif grep -xq 'down' /sys/class/net/w*/operstate 2>/dev/null; then
    # wifi is not connected
    if grep -xq '0x1003' /sys/class/net/w*/flags; then
      # no hotspot available
      printf "󰛵"
    else
      # wifi disabled
      printf "󰯡"
    fi
  else
    # no wifi interface
    printf "󰯡"
  fi
  
  # ethernet
  printf "%s\n" "$(sed "s/down/󰅛/;s/up/󰱓/" /sys/class/net/e*/operstate 2>/dev/null | tr -d '\n')"
}

trap "toggle_wifi" USR1
trap "toggle_speed" USR2

while true; do
  status
  sleep 5 &
  wait
done
